import os
from dotenv import load_dotenv

load_dotenv()

HF_API_KEY = os.getenv("HF_API_KEY")
ROUTER_MODEL = os.getenv("ROUTER_MODEL")

DEFAULT_RESULTS_FOLDER = os.getenv("DEFAULT_RESULTS_FOLDER")
DEFAULT_MERGED_FILE = os.getenv("DEFAULT_MERGED_FILE")
DEFAULT_CLEAN_FILE = os.getenv("DEFAULT_CLEAN_FILE")
DEFAULT_SENTIMENT_FILE = os.getenv("DEFAULT_SENTIMENT_FILE")
DEFAULT_EMOTION_FILE = os.getenv("DEFAULT_EMOTION_FILE")
DEFAULT_TOPIC_FILE = os.getenv("DEFAULT_TOPIC_FILE")
DEFAULT_TOPIC_KEYWORDS_FILE = os.getenv("DEFAULT_TOPIC_KEYWORDS_FILE")

CRAWL_LIMIT_PER_QUERY = int(os.getenv("CRAWL_LIMIT_PER_QUERY"))
CRAWL_STOP_AFTER_NO_NEW = int(os.getenv("CRAWL_STOP_AFTER_NO_NEW"))
CRAWL_PAUSE_LIMIT = int(os.getenv("CRAWL_PAUSE_LIMIT"))
CRAWL_DEBUGGER_ADDRESS = os.getenv("CRAWL_DEBUGGER_ADDRESS")

CRAWL_HUMAN_PAUSE_PROB = float(os.getenv("CRAWL_HUMAN_PAUSE_PROB", "0.10"))
CRAWL_HUMAN_PAUSE_MIN = float(os.getenv("CRAWL_HUMAN_PAUSE_MIN", "2"))
CRAWL_HUMAN_PAUSE_MAX = float(os.getenv("CRAWL_HUMAN_PAUSE_MAX", "6"))

CRAWL_SHORT_MOVE_PROB = float(os.getenv("CRAWL_SHORT_MOVE_PROB", "0.15"))

CRAWL_SCROLL_SLEEP_MIN = float(os.getenv("CRAWL_SCROLL_SLEEP_MIN", "0.8"))
CRAWL_SCROLL_SLEEP_MAX = float(os.getenv("CRAWL_SCROLL_SLEEP_MAX", "1.8"))

CRAWL_BETWEEN_QUERY_SLEEP_MIN = float(os.getenv("CRAWL_BETWEEN_QUERY_SLEEP_MIN", "10"))
CRAWL_BETWEEN_QUERY_SLEEP_MAX = float(os.getenv("CRAWL_BETWEEN_QUERY_SLEEP_MAX", "20"))
